name: myfootball
description: FootballTeam develop by TuyenNguyen.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: ^0.15.7
  timeago: ^2.0.10
  flutter_swiper: ^1.1.4
  shared_preferences: ^0.4.3
  dio: ^2.1.2
  image_picker: ^0.6.0+2
  firebase_storage: ^3.0.6
  firebase_core: ^0.4.0+9
  firebase_messaging: ^5.1.5
  cloud_firestore: ^0.12.11
  firebase_auth: ^0.15.0+1
  flutter_rating_bar: ^3.0.0
  device_info: ^0.4.0+2
  provider: ^3.1.0
  url_launcher: ^5.1.4
  geolocator: ^5.1.4+1
  permission_handler: ^3.0.1
  google_maps_flutter: ^0.5.21+7
  sqflite: ^1.1.7+1
  queries: ^0.1.12
  mask_text_input_formatter: ^1.0.5
  percent_indicator: ^2.1.1+1
  like_button: ^0.1.9
  unicorndial: ^1.1.5
  month_picker_dialog: ^0.3.0
  webfeed: ^0.4.2
  html: ^0.13.4+1
  share: ^0.6.3+4
  pull_to_refresh: ^1.5.7
  dash_chat: ^1.0.9

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/ic_logo_copy.jpg'

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - assets/data/

  fonts:
  - family: regular
    fonts:
      - asset: assets/fonts/Muli-Regular.ttf
  - family: italic
    fonts:
      - asset: assets/fonts/Muli-Italic.ttf
  - family: medium
    fonts:
      - asset: assets/fonts/Muli-Medium.ttf
  - family: medium-italic
    fonts:
      - asset: assets/fonts/Muli-MediumItalic.ttf
  - family: semi-bold
    fonts:
      - asset: assets/fonts/Muli-SemiBold.ttf
  - family: semi-bold-italic
    fonts:
      - asset: assets/fonts/Muli-SemiBoldItalic.ttf
  - family: bold
    fonts:
      - asset: assets/fonts/Muli-Bold.ttf
  - family: bold-italic
    fonts:
      - asset: assets/fonts/Muli-BoldItalic.ttf