name: myfootball
description: FootballTeam develop by TuyenNguyen.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.0
  timeago: ^2.0.22
  flutter_swiper: ^1.1.6
  shared_preferences: ^0.4.3
  dio: ^3.0.8
  image_picker: ^0.6.0+2
  firebase_storage: ^3.1.1
  firebase_core: ^0.4.3+1
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.13.0+1
  firebase_auth: ^0.15.3
  flutter_rating_bar: ^3.0.0
  device_info: ^0.4.1+4
  provider: ^3.2.0
  url_launcher: ^5.4.1
  geolocator: ^5.1.5
  permission_handler: ^4.0.0
  google_maps_flutter: ^0.5.21+15
  sqflite: ^1.2.0
  queries: ^0.1.12
  mask_text_input_formatter: ^1.0.5
  percent_indicator: ^2.1.1+1
  like_button: ^0.1.9
  unicorndial: ^1.1.5
  month_picker_dialog: ^0.3.0
  webfeed: ^0.4.2
  html: ^0.13.4+1
  share: ^0.6.3+4
  pull_to_refresh: ^1.5.7
  dash_chat: ^1.0.9
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.7.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/ic_logo_copy.jpg'

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - assets/data/

  fonts:
  - family: regular
    fonts:
      - asset: assets/fonts/Muli-Regular.ttf
  - family: italic
    fonts:
      - asset: assets/fonts/Muli-Italic.ttf
  - family: medium
    fonts:
      - asset: assets/fonts/Muli-Medium.ttf
  - family: medium-italic
    fonts:
      - asset: assets/fonts/Muli-MediumItalic.ttf
  - family: semi-bold
    fonts:
      - asset: assets/fonts/Muli-SemiBold.ttf
  - family: semi-bold-italic
    fonts:
      - asset: assets/fonts/Muli-SemiBoldItalic.ttf
  - family: bold
    fonts:
      - asset: assets/fonts/Muli-Bold.ttf
  - family: bold-italic
    fonts:
      - asset: assets/fonts/Muli-BoldItalic.ttf